---
  - name: Восстановление n8n из резервной копии
    hosts: n8n_vps
    become: yes

    vars_prompt:
      - name: backup_file_name
        prompt: "Введите точное имя файла бекапа для восстановления (например, backup-n8n.server.com-2025-07-23T12_00_00.tar.gz)"
        private: no

    roles:
      - n8n_restore