---
- name: Создать архив данных
  community.general.archive:
    path:
      - /var/lib/docker/volumes/n8n_data
      - /var/lib/docker/volumes/traefik_data
    dest: "/tmp/backup-{{ inventory_hostname }}-{{ ansible_date_time.iso8601 | regex_replace(':', '_') }}.tar.gz"
    format: gz
    owner: root
    group: root
    mode: '0600'

- name: Загрузить резервную копию на Google Drive через rclone
  shell: "rclone copy /tmp/backup-{{ inventory_hostname }}-{{ ansible_date_time.iso8601 | regex_replace(':', '_') }}.tar.gz gdrive03:backup_services/n8n/"
  args:
    executable: /bin/bash

- name: Удалить локальный архив после загрузки
  file:
    path: "/tmp/backup-{{ inventory_hostname }}-{{ ansible_date_time.iso8601 | regex_replace(':', '_') }}.tar.gz"
    state: absent