---
- name: "Ensure Python dependencies for PostgreSQL are installed"
  become: yes
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
    
- name: "Ensure PostgreSQL client tools (psql, pg_dump) are installed on the host"
  become: yes
  ansible.builtin.apt:
    name: postgresql-client
    state: present
    update_cache: yes
    
- name: 1. Create directory for config and certs
  become: yes
  ansible.builtin.file:
    path: "{{ postgres_config_path }}/certs"
    state: directory
    mode: '0755'

- name: 2. Copy SSL certificates with correct permissions
  become: yes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ postgres_config_path }}/certs/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: 999
    group: 999
  with_items:
    - { src: 'certs/server.crt', dest: 'server.crt', mode: '0644' }
    - { src: 'certs/server.key', dest: 'server.key', mode: '0600' }

- name: 3. Create SQL file for SSL settings from template
  become: yes
  ansible.builtin.template:
    src: "custom-settings.sql.j2"
    dest: "{{ postgres_config_path }}/custom-settings.sql"
    mode: '0644'

- name: 4. Ensure PostgreSQL data volume exists
  community.docker.docker_volume:
    name: "{{ postgres_volume_name }}"
    state: present

- name: 5. Deploy PostgreSQL container
  community.docker.docker_compose_v2:
    project_name: "{{ postgres_project_name }}"
    definition: "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present

- name: 6. Configure firewall (UFW)
  become: yes
  block:
    - name: Allow SSH connections (important!)
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Allow PostgreSQL port only from AppSheet IPs
      community.general.ufw:
        rule: allow
        src: "{{ item }}"
        port: '5432'
        proto: tcp
      with_items:
        - '34.64.0.0/12'
        - '35.224.0.0/12'
        - '64.18.0.0/16'
        - '104.155.128.0/17'
        - '130.211.0.0/16'

    - name: Enable UFW firewall if it is not active
      community.general.ufw:
        state: enabled