---
# tasks file for restore_n8n

- name: 1. Остановить и удалить контейнеры n8n и traefik
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - n8n
    - traefik
  ignore_errors: yes
  tags:
    - restore

- name: 2. Очистить старые данные в вольюмах
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    # Мы удаляем содержимое, а не сами вольюмы, чтобы Docker не ругался
    - /var/lib/docker/volumes/n8n_data/_data
    - /var/lib/docker/volumes/traefik_data/_data
  tags:
    - restore

- name: 3. Скачать указанный бекап с Google Drive
  ansible.builtin.shell: "rclone copy 'gdrive03:backup_test/srv_test/{{ backup_file_name }}' /tmp/"
  args:
    executable: /bin/bash
  tags:
    - restore

- name: 4. Распаковать архив с данными в корень файловой системы
  ansible.builtin.unarchive:
    src: "/tmp/{{ backup_file_name }}"
    dest: /
    remote_src: yes
  tags:
    - restore

- name: 5. Установить правильные права для данных n8n
  ansible.builtin.file:
    path: /var/lib/docker/volumes/n8n_data/_data
    state: directory
    recurse: yes
    # n8n внутри контейнера работает под пользователем node (uid 1000)
    owner: '1000'
    group: '1000'
  tags:
    - restore

- name: 6. Удалить локальный архив после распаковки
  ansible.builtin.file:
    path: "/tmp/{{ backup_file_name }}"
    state: absent
  tags:
    - restore

- name: "ЗАВЕРШЕНИЕ: Данные восстановлены. Запустите деплой n8n"
  ansible.builtin.debug:
    msg: "Данные из файла '{{ backup_file_name }}' успешно восстановлены. Теперь запустите ваш основной плейбук для деплоя, чтобы поднять все сервисы."
  tags:
    - restore
